# Site settings
title: Chrisanthropic
email: 

description: > # this means to ignore newlines until "baseurl:"
  Playing with things and documenting it.
  
baseurl: ""
url: "http://www.chrisanthropic.com"

twitter_username:
github_username: chrisanthropic

# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site