# Site settings
title: Chrisanthropic
email:
author: Chrisanthropic

keywords: jekyll, jekyll theme, portfolio theme, artist theme
description: >
  Playing with things and documenting it.

github:
  url: "https://www.chrisanthropic.com"

header: images/logo.png

# Formspree contact Form
#contact_form: "https://formspree.io/ctarwater@chrisanthropic.com"


# Exclude our ruby stuff
exclude: [.bundle, .vendor, .bin, .git, starving-artist.gemspec, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, starving-artist-jekyll-theme-*.gem]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Plugins
gems:
  - jekyll-feed

feed:
  path: atom.xml

include: ['_pages', '_redirects']

permalink: /blog/:year/:title/

collections:
  - galleries

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                                #enter your App ID
facebook_locale: en_US
facebook_page:                                  #the URL of your Facebook Page
facebook_image: images/author.jpg                      #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: 
twitter_card: true
twitter_image: images/author.jpg                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
